- hosts: mysql_cluster_mgm
  environment:
        http_proxy: http://10.222.192.4:8080
        https_proxy: http://10.222.192.4:8080
  roles:
  - mysql-cluster-mgm

- hosts: mysql_cluster_data
  environment:
        http_proxy: http://10.222.192.4:8080
        https_proxy: http://10.222.192.4:8080
  roles:
  - mysql-cluster-data

- hosts: mysql_cluster_sql
  environment:
        http_proxy: http://10.222.192.4:8080
        https_proxy: http://10.222.192.4:8080
  roles:
  - mysql-cluster-sql
